version: '3'

tasks:
  build:
    env:
      GORELEASER_CURRENT_TAG: "v0.0.0"
    cmd: goreleaser build --snapshot --clean --single-target --output terraform-provider-bluestonepim

  codegen:
    cmds:
      - task: codegen:pim

  codegen:pim:
    dir: internal/sdk/pim
    cmds:
      - oapi-codegen -config config.yaml https://docs.api.bluestonepim.com/openapi/66557c17ba1fbb0011cf1af6

  examples:
    dir: examples
    deps:
      - build-local
    cmds:
      - rm -f .terraform.lock.hcl
      - terraform init
      - terraform apply

  format:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - go test -v ./...

  docs:
    cmds:
      - go generate

  coverage:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -func=coverage.txt
