version: '3'

tasks:
  build:
    env:
      GORELEASER_CURRENT_TAG: "v0.0.0"
    cmd: goreleaser build --snapshot --clean --single-target --output terraform-provider-bluestonepim

  format:
    cmds:
      - go fmt ./...
      - terraform fmt -recursive ./examples

  test:
    cmds:
      - go test -v ./...

  docs:
    cmds:
      - go generate ./...

  coverage:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -func=coverage.txt
