version: '3'

tasks:
  build-local:
    cmds:
      - go build -o terraform-provider-{{ .NAME }}_{{ .VERSION }}
      - mkdir -p ~/.terraform.d/plugins/registry.terraform.io/labd/{{ .NAME }}/{{ .VERSION }}/{{ .PLATFORM }}/
      - mv terraform-provider-{{ .NAME }}_{{ .VERSION }} ~/.terraform.d/plugins/registry.terraform.io/labd/{{ .NAME }}/{{ .VERSION }}/{{ .PLATFORM }}/terraform-provider-{{ .NAME }}_v{{ .VERSION }}
      - cmd: codesign --deep --force -s - ~/.terraform.d/plugins/registry.terraform.io/labd/{{ .NAME }}/{{ .VERSION }}/{{ .PLATFORM }}/terraform-provider-{{ .NAME }}_v{{ .VERSION }}
        platforms: [darwin]
    vars:
      VERSION: 99.0.0
      NAME: bluestonepim
      PLATFORM:
        sh: echo "$(go env GOOS)_$(go env GOARCH)"

  codegen:
    dir: internal/sdk/
    cmds:
      - oapi-codegen -config config-pim.yaml ../../specs/api-docs.yaml


  examples:
    dir: examples
    deps:
      - build-local
    cmds:
      - rm -f .terraform.lock.hcl
      - terraform init
      - terraform apply

  format:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - go test -v ./...

  docs:
    cmds:
      - go generate

  coverage:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -func=coverage.txt
